name: logdoor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Network & API
  dio: ^5.3.2
  pocketbase: ^0.22.0
  connectivity_plus: ^4.0.2

  # UI Components
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_slidable:
    ^3.0.0

    # Authentication
  local_auth: ^2.1.6
  flutter_secure_storage:
    ^8.0.0

    # Utilities
  uuid: ^3.0.7
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  pdf: ^3.10.4
  printing: ^5.11.0
  shared_preferences: ^2.2.2

  # QR code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1

  # Location
  geolocator: ^10.1.0

  # Offline support
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  share_plus: ^10.1.4
  pin_code_fields: ^8.0.1
  flutter_pdfview: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
